version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.43.1-jammy
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps

      - run:
          name: Run Playwright tests
          command: npx playwright test

      - run:
          name: Show test report location
          command: echo "Open the report with: npx playwright show-report"

      - store_artifacts:
          path: playwright-report
          destination: playwright-report
